{% set name = "azure-cli-core" %}
{% set version = "2.40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35ae525aa097a676c11f0469cadba1f9692d20098b1a227ec7a996bf18986bd7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6.0
    - pip
  run:
    - python
    - argcomplete >=1.8,<2.dev0
    - azure-cli-telemetry ==1.0.8.*
    - azure-mgmt-core >=1.2.0,<2
    - cryptography
    - humanfriendly >=10.0,<11.dev0
    - jmespath
    - knack >=0.10.0,<0.11.dev0
    - msal_extensions >=1.0.0,<1.1.dev0
    - msal ==1.18.0b1
    - msrestazure >=0.6.4,<0.7.dev0
    - packaging >=20.9,<22.0
    - paramiko >=2.0.8,<3.0.0
    - pkginfo >=1.5.0.1
    - psutil >=5.9,<6.dev0  # [not cygwin]
    - pyjwt >=2.1.0
    - pyopenssl >=17.1.0
    - requests
test:
  imports:
    - azure
    - azure.cli
    - azure.cli.core
    - azure.cli.core.commands
    - azure.cli.core.extension
    - azure.cli.core.profiles

about:
  home: https://github.com/Azure/azure-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Command-Line Tools Core Module

  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - andreyz4k
